### ISSUE TITLE
dynsections.js is missing

### ISSUE THREAD

**Issue by cchan** [Kitware/paraview-docs#12]
Opening any of the paraview docs fails with

```
Loading failed for the <script> with source "https://kitware.github.io/paraview-docs/latest/cxx/dynsections.js".
```

**Comment by utkarshayachit** [comment]
thanks for reporting! fix coming shortly.

**Comment by utkarshayachit** [comment]
@jourdain, when you get the chance can you please see what's going on here. I manually put the dynsections.js in each of the sub folders but it still fails to load. thanks.

**Comment by jourdain** [comment]
Seems to be working for me.

**Comment by jourdain** [comment]
But the Python section seems messed up

**Comment by jourdain** [comment]
It seems that /v5.8.1/python/_static/** is missing

**Comment by utkarshayachit** [comment]
all issues have been addressed.
