### ISSUE TITLE
Broken hyperlinks in Python documentation search results

### ISSUE THREAD

**Issue by mirenradia** [Kitware/paraview-docs#16]
When I search for something in the Python documentation (e.g. [Background](https://kitware.github.io/paraview-docs/v5.9.1/python/search.html?q=Background)), the hyperlinks in the search results are broken (e.g. [https://kitware.github.io/paraview-docs/v5.9.1/python/paraview.simpleundefined?highlight=background](https://kitware.github.io/paraview-docs/v5.9.1/python/paraview.simpleundefined?highlight=background)) as they seem to contain a superfluous `undefined` in them. Removing `undefined` from the URL takes you to the correct place.

This seems to affect v5.9.0, v5.9.1, latest and nightly at the moment.

**Comment by cquammen** [comment]
This is now fixed.
