### ISSUE TITLE
Periodically squashing the gh-pages branch of this repo

### ISSUE THREAD

**Issue by vicentebolea** [Kitware/paraview-docs#18]
With each new pushed commit the times to clone the gh-pages are increasingly growing, while git shallow clones helps with this, there are many limitations using shallow clones.

I propose to setup a small automatized job, using the github CI, to nightly squash the gh-pages branch to keep the most recent last ten commits.

This will dramatically reduce the cloning time and therefore all of our ParaView CI jobs that generate and pushed the docs here.

@cquammen

**Comment by vicentebolea** [comment]
@jourdain good to know that you have the same use case for vtk.js :)

I will follow up with PR using something like your script only for the gh-pages branch.

**Comment by cquammen** [comment]
Sounds good to me.
